name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Lint
        run: npm run lint
        working-directory: ./backend

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run tests
        run: npm test -- --json --outputFile=test-results.json
        working-directory: ./backend

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./backend/test-results.txt

  build:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Build app
        run: npm run build
        working-directory: ./backend

  deploy:
      runs-on: ubuntu-latest
      needs: build
      if: success()
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Deploy to Render
          uses: render-action/render-action@v1
          with:
            service-id: srv-d20einmmcj7s73b35qm0
            api-key: ${{ secrets.RENDER_API_KEY }}
          env:
            RENDER_GIT_REPO: https://github.com/hadiuzzaman909/mini-job-board.git